# 外部可替换资源：将路径改为你自己的 BMP 文件即可
# 要求：BMP 24/32bpp，未压缩（程序会做格式检查）

background=/share/pictures/projectn.bmp

icon0=/share/pictures/projectn.bmp
icon1=/share/pictures/projectn.bmp
icon2=/share/pictures/projectn.bmp
icon3=/share/pictures/projectn.bmp
icon4=/share/pictures/projectn.bmp
icon5=/share/pictures/projectn.bmp
